/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClerkRouteRouteImport } from './routes/clerk/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedNetworkMapRouteImport } from './routes/_authenticated/network-map'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as ClerkAuthenticatedRouteRouteImport } from './routes/clerk/_authenticated/route'
import { Route as ClerkauthRouteRouteImport } from './routes/clerk/(auth)/route'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTicketsIndexRouteImport } from './routes/_authenticated/tickets/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSystemToolsIndexRouteImport } from './routes/_authenticated/system-tools/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedReportsIndexRouteImport } from './routes/_authenticated/reports/index'
import { Route as AuthenticatedPppoeIndexRouteImport } from './routes/_authenticated/pppoe/index'
import { Route as AuthenticatedOltIndexRouteImport } from './routes/_authenticated/olt/index'
import { Route as AuthenticatedOdpIndexRouteImport } from './routes/_authenticated/odp/index'
import { Route as AuthenticatedMonitoringIndexRouteImport } from './routes/_authenticated/monitoring/index'
import { Route as AuthenticatedLogsIndexRouteImport } from './routes/_authenticated/logs/index'
import { Route as AuthenticatedInventoryIndexRouteImport } from './routes/_authenticated/inventory/index'
import { Route as AuthenticatedHotspotIndexRouteImport } from './routes/_authenticated/hotspot/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedGenieacsIndexRouteImport } from './routes/_authenticated/genieacs/index'
import { Route as AuthenticatedFinanceIndexRouteImport } from './routes/_authenticated/finance/index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedBillingIndexRouteImport } from './routes/_authenticated/billing/index'
import { Route as AuthenticatedAutomationIndexRouteImport } from './routes/_authenticated/automation/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedAcsIndexRouteImport } from './routes/_authenticated/acs/index'
import { Route as ClerkAuthenticatedUserManagementRouteImport } from './routes/clerk/_authenticated/user-management'
import { Route as ClerkauthSignUpRouteImport } from './routes/clerk/(auth)/sign-up'
import { Route as ClerkauthSignInRouteImport } from './routes/clerk/(auth)/sign-in'
import { Route as AuthenticatedSettingsRoutersRouteImport } from './routes/_authenticated/settings/routers'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAdminsRouteImport } from './routes/_authenticated/settings/admins'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedPppoeSecretsRouteImport } from './routes/_authenticated/pppoe/secrets'
import { Route as AuthenticatedPppoeProfilesRouteImport } from './routes/_authenticated/pppoe/profiles'
import { Route as AuthenticatedPppoeOfflineRouteImport } from './routes/_authenticated/pppoe/offline'
import { Route as AuthenticatedPppoeActiveRouteImport } from './routes/_authenticated/pppoe/active'
import { Route as AuthenticatedOdpCapacityRouteImport } from './routes/_authenticated/odp/capacity'
import { Route as AuthenticatedGenieacsSettingsRouteImport } from './routes/_authenticated/genieacs/settings'
import { Route as AuthenticatedFinanceReportRouteImport } from './routes/_authenticated/finance/report'
import { Route as AuthenticatedFinanceReceivableRouteImport } from './routes/_authenticated/finance/receivable'
import { Route as AuthenticatedFinanceBillingRouteImport } from './routes/_authenticated/finance/billing'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedCustomersOverviewRouteImport } from './routes/_authenticated/customers/overview'
import { Route as AuthenticatedCustomersOnlineRouteImport } from './routes/_authenticated/customers/online'
import { Route as AuthenticatedCustomersOfflineRouteImport } from './routes/_authenticated/customers/offline'
import { Route as AuthenticatedCustomersImportExportRouteImport } from './routes/_authenticated/customers/import-export'
import { Route as AuthenticatedCustomersByProfileRouteImport } from './routes/_authenticated/customers/by-profile'

const ClerkRouteRoute = ClerkRouteRouteImport.update({
  id: '/clerk',
  path: '/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNetworkMapRoute = AuthenticatedNetworkMapRouteImport.update({
  id: '/network-map',
  path: '/network-map',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ClerkAuthenticatedRouteRoute = ClerkAuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const ClerkauthRouteRoute = ClerkauthRouteRouteImport.update({
  id: '/(auth)',
  getParentRoute: () => ClerkRouteRoute,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTicketsIndexRoute =
  AuthenticatedTicketsIndexRouteImport.update({
    id: '/tickets/',
    path: '/tickets/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSystemToolsIndexRoute =
  AuthenticatedSystemToolsIndexRouteImport.update({
    id: '/system-tools/',
    path: '/system-tools/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedReportsIndexRoute =
  AuthenticatedReportsIndexRouteImport.update({
    id: '/reports/',
    path: '/reports/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPppoeIndexRoute = AuthenticatedPppoeIndexRouteImport.update({
  id: '/pppoe/',
  path: '/pppoe/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOltIndexRoute = AuthenticatedOltIndexRouteImport.update({
  id: '/olt/',
  path: '/olt/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOdpIndexRoute = AuthenticatedOdpIndexRouteImport.update({
  id: '/odp/',
  path: '/odp/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMonitoringIndexRoute =
  AuthenticatedMonitoringIndexRouteImport.update({
    id: '/monitoring/',
    path: '/monitoring/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLogsIndexRoute = AuthenticatedLogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInventoryIndexRoute =
  AuthenticatedInventoryIndexRouteImport.update({
    id: '/inventory/',
    path: '/inventory/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHotspotIndexRoute =
  AuthenticatedHotspotIndexRouteImport.update({
    id: '/hotspot/',
    path: '/hotspot/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGenieacsIndexRoute =
  AuthenticatedGenieacsIndexRouteImport.update({
    id: '/genieacs/',
    path: '/genieacs/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceIndexRoute =
  AuthenticatedFinanceIndexRouteImport.update({
    id: '/finance/',
    path: '/finance/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingIndexRoute =
  AuthenticatedBillingIndexRouteImport.update({
    id: '/billing/',
    path: '/billing/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAutomationIndexRoute =
  AuthenticatedAutomationIndexRouteImport.update({
    id: '/automation/',
    path: '/automation/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAcsIndexRoute = AuthenticatedAcsIndexRouteImport.update({
  id: '/acs/',
  path: '/acs/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ClerkAuthenticatedUserManagementRoute =
  ClerkAuthenticatedUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => ClerkAuthenticatedRouteRoute,
  } as any)
const ClerkauthSignUpRoute = ClerkauthSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const ClerkauthSignInRoute = ClerkauthSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => ClerkauthRouteRoute,
} as any)
const AuthenticatedSettingsRoutersRoute =
  AuthenticatedSettingsRoutersRouteImport.update({
    id: '/routers',
    path: '/routers',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAdminsRoute =
  AuthenticatedSettingsAdminsRouteImport.update({
    id: '/admins',
    path: '/admins',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedPppoeSecretsRoute =
  AuthenticatedPppoeSecretsRouteImport.update({
    id: '/pppoe/secrets',
    path: '/pppoe/secrets',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPppoeProfilesRoute =
  AuthenticatedPppoeProfilesRouteImport.update({
    id: '/pppoe/profiles',
    path: '/pppoe/profiles',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPppoeOfflineRoute =
  AuthenticatedPppoeOfflineRouteImport.update({
    id: '/pppoe/offline',
    path: '/pppoe/offline',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPppoeActiveRoute =
  AuthenticatedPppoeActiveRouteImport.update({
    id: '/pppoe/active',
    path: '/pppoe/active',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOdpCapacityRoute =
  AuthenticatedOdpCapacityRouteImport.update({
    id: '/odp/capacity',
    path: '/odp/capacity',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGenieacsSettingsRoute =
  AuthenticatedGenieacsSettingsRouteImport.update({
    id: '/genieacs/settings',
    path: '/genieacs/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceReportRoute =
  AuthenticatedFinanceReportRouteImport.update({
    id: '/finance/report',
    path: '/finance/report',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceReceivableRoute =
  AuthenticatedFinanceReceivableRouteImport.update({
    id: '/finance/receivable',
    path: '/finance/receivable',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFinanceBillingRoute =
  AuthenticatedFinanceBillingRouteImport.update({
    id: '/finance/billing',
    path: '/finance/billing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersOverviewRoute =
  AuthenticatedCustomersOverviewRouteImport.update({
    id: '/customers/overview',
    path: '/customers/overview',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersOnlineRoute =
  AuthenticatedCustomersOnlineRouteImport.update({
    id: '/customers/online',
    path: '/customers/online',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersOfflineRoute =
  AuthenticatedCustomersOfflineRouteImport.update({
    id: '/customers/offline',
    path: '/customers/offline',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersImportExportRoute =
  AuthenticatedCustomersImportExportRouteImport.update({
    id: '/customers/import-export',
    path: '/customers/import-export',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersByProfileRoute =
  AuthenticatedCustomersByProfileRouteImport.update({
    id: '/customers/by-profile',
    path: '/customers/by-profile',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/network-map': typeof AuthenticatedNetworkMapRoute
  '/customers/by-profile': typeof AuthenticatedCustomersByProfileRoute
  '/customers/import-export': typeof AuthenticatedCustomersImportExportRoute
  '/customers/offline': typeof AuthenticatedCustomersOfflineRoute
  '/customers/online': typeof AuthenticatedCustomersOnlineRoute
  '/customers/overview': typeof AuthenticatedCustomersOverviewRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/finance/billing': typeof AuthenticatedFinanceBillingRoute
  '/finance/receivable': typeof AuthenticatedFinanceReceivableRoute
  '/finance/report': typeof AuthenticatedFinanceReportRoute
  '/genieacs/settings': typeof AuthenticatedGenieacsSettingsRoute
  '/odp/capacity': typeof AuthenticatedOdpCapacityRoute
  '/pppoe/active': typeof AuthenticatedPppoeActiveRoute
  '/pppoe/offline': typeof AuthenticatedPppoeOfflineRoute
  '/pppoe/profiles': typeof AuthenticatedPppoeProfilesRoute
  '/pppoe/secrets': typeof AuthenticatedPppoeSecretsRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/admins': typeof AuthenticatedSettingsAdminsRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/routers': typeof AuthenticatedSettingsRoutersRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/acs/': typeof AuthenticatedAcsIndexRoute
  '/apps/': typeof AuthenticatedAppsIndexRoute
  '/automation/': typeof AuthenticatedAutomationIndexRoute
  '/billing/': typeof AuthenticatedBillingIndexRoute
  '/chats/': typeof AuthenticatedChatsIndexRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/finance/': typeof AuthenticatedFinanceIndexRoute
  '/genieacs/': typeof AuthenticatedGenieacsIndexRoute
  '/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/hotspot/': typeof AuthenticatedHotspotIndexRoute
  '/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/logs/': typeof AuthenticatedLogsIndexRoute
  '/monitoring/': typeof AuthenticatedMonitoringIndexRoute
  '/odp/': typeof AuthenticatedOdpIndexRoute
  '/olt/': typeof AuthenticatedOltIndexRoute
  '/pppoe/': typeof AuthenticatedPppoeIndexRoute
  '/reports/': typeof AuthenticatedReportsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/system-tools/': typeof AuthenticatedSystemToolsIndexRoute
  '/tasks/': typeof AuthenticatedTasksIndexRoute
  '/tickets/': typeof AuthenticatedTicketsIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesByTo {
  '/clerk': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/network-map': typeof AuthenticatedNetworkMapRoute
  '/': typeof AuthenticatedIndexRoute
  '/customers/by-profile': typeof AuthenticatedCustomersByProfileRoute
  '/customers/import-export': typeof AuthenticatedCustomersImportExportRoute
  '/customers/offline': typeof AuthenticatedCustomersOfflineRoute
  '/customers/online': typeof AuthenticatedCustomersOnlineRoute
  '/customers/overview': typeof AuthenticatedCustomersOverviewRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/finance/billing': typeof AuthenticatedFinanceBillingRoute
  '/finance/receivable': typeof AuthenticatedFinanceReceivableRoute
  '/finance/report': typeof AuthenticatedFinanceReportRoute
  '/genieacs/settings': typeof AuthenticatedGenieacsSettingsRoute
  '/odp/capacity': typeof AuthenticatedOdpCapacityRoute
  '/pppoe/active': typeof AuthenticatedPppoeActiveRoute
  '/pppoe/offline': typeof AuthenticatedPppoeOfflineRoute
  '/pppoe/profiles': typeof AuthenticatedPppoeProfilesRoute
  '/pppoe/secrets': typeof AuthenticatedPppoeSecretsRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/admins': typeof AuthenticatedSettingsAdminsRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/settings/routers': typeof AuthenticatedSettingsRoutersRoute
  '/clerk/sign-in': typeof ClerkauthSignInRoute
  '/clerk/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/acs': typeof AuthenticatedAcsIndexRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/automation': typeof AuthenticatedAutomationIndexRoute
  '/billing': typeof AuthenticatedBillingIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/finance': typeof AuthenticatedFinanceIndexRoute
  '/genieacs': typeof AuthenticatedGenieacsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/hotspot': typeof AuthenticatedHotspotIndexRoute
  '/inventory': typeof AuthenticatedInventoryIndexRoute
  '/logs': typeof AuthenticatedLogsIndexRoute
  '/monitoring': typeof AuthenticatedMonitoringIndexRoute
  '/odp': typeof AuthenticatedOdpIndexRoute
  '/olt': typeof AuthenticatedOltIndexRoute
  '/pppoe': typeof AuthenticatedPppoeIndexRoute
  '/reports': typeof AuthenticatedReportsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/system-tools': typeof AuthenticatedSystemToolsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/tickets': typeof AuthenticatedTicketsIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/clerk': typeof ClerkRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/clerk/(auth)': typeof ClerkauthRouteRouteWithChildren
  '/clerk/_authenticated': typeof ClerkAuthenticatedRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/network-map': typeof AuthenticatedNetworkMapRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/customers/by-profile': typeof AuthenticatedCustomersByProfileRoute
  '/_authenticated/customers/import-export': typeof AuthenticatedCustomersImportExportRoute
  '/_authenticated/customers/offline': typeof AuthenticatedCustomersOfflineRoute
  '/_authenticated/customers/online': typeof AuthenticatedCustomersOnlineRoute
  '/_authenticated/customers/overview': typeof AuthenticatedCustomersOverviewRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/finance/billing': typeof AuthenticatedFinanceBillingRoute
  '/_authenticated/finance/receivable': typeof AuthenticatedFinanceReceivableRoute
  '/_authenticated/finance/report': typeof AuthenticatedFinanceReportRoute
  '/_authenticated/genieacs/settings': typeof AuthenticatedGenieacsSettingsRoute
  '/_authenticated/odp/capacity': typeof AuthenticatedOdpCapacityRoute
  '/_authenticated/pppoe/active': typeof AuthenticatedPppoeActiveRoute
  '/_authenticated/pppoe/offline': typeof AuthenticatedPppoeOfflineRoute
  '/_authenticated/pppoe/profiles': typeof AuthenticatedPppoeProfilesRoute
  '/_authenticated/pppoe/secrets': typeof AuthenticatedPppoeSecretsRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/admins': typeof AuthenticatedSettingsAdminsRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/settings/routers': typeof AuthenticatedSettingsRoutersRoute
  '/clerk/(auth)/sign-in': typeof ClerkauthSignInRoute
  '/clerk/(auth)/sign-up': typeof ClerkauthSignUpRoute
  '/clerk/_authenticated/user-management': typeof ClerkAuthenticatedUserManagementRoute
  '/_authenticated/acs/': typeof AuthenticatedAcsIndexRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/automation/': typeof AuthenticatedAutomationIndexRoute
  '/_authenticated/billing/': typeof AuthenticatedBillingIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/finance/': typeof AuthenticatedFinanceIndexRoute
  '/_authenticated/genieacs/': typeof AuthenticatedGenieacsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/hotspot/': typeof AuthenticatedHotspotIndexRoute
  '/_authenticated/inventory/': typeof AuthenticatedInventoryIndexRoute
  '/_authenticated/logs/': typeof AuthenticatedLogsIndexRoute
  '/_authenticated/monitoring/': typeof AuthenticatedMonitoringIndexRoute
  '/_authenticated/odp/': typeof AuthenticatedOdpIndexRoute
  '/_authenticated/olt/': typeof AuthenticatedOltIndexRoute
  '/_authenticated/pppoe/': typeof AuthenticatedPppoeIndexRoute
  '/_authenticated/reports/': typeof AuthenticatedReportsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/system-tools/': typeof AuthenticatedSystemToolsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/tickets/': typeof AuthenticatedTicketsIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clerk'
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/network-map'
    | '/customers/by-profile'
    | '/customers/import-export'
    | '/customers/offline'
    | '/customers/online'
    | '/customers/overview'
    | '/errors/$error'
    | '/finance/billing'
    | '/finance/receivable'
    | '/finance/report'
    | '/genieacs/settings'
    | '/odp/capacity'
    | '/pppoe/active'
    | '/pppoe/offline'
    | '/pppoe/profiles'
    | '/pppoe/secrets'
    | '/settings/account'
    | '/settings/admins'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/settings/routers'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/acs/'
    | '/apps/'
    | '/automation/'
    | '/billing/'
    | '/chats/'
    | '/customers/'
    | '/finance/'
    | '/genieacs/'
    | '/help-center/'
    | '/hotspot/'
    | '/inventory/'
    | '/logs/'
    | '/monitoring/'
    | '/odp/'
    | '/olt/'
    | '/pppoe/'
    | '/reports/'
    | '/settings/'
    | '/system-tools/'
    | '/tasks/'
    | '/tickets/'
    | '/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/clerk'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/network-map'
    | '/'
    | '/customers/by-profile'
    | '/customers/import-export'
    | '/customers/offline'
    | '/customers/online'
    | '/customers/overview'
    | '/errors/$error'
    | '/finance/billing'
    | '/finance/receivable'
    | '/finance/report'
    | '/genieacs/settings'
    | '/odp/capacity'
    | '/pppoe/active'
    | '/pppoe/offline'
    | '/pppoe/profiles'
    | '/pppoe/secrets'
    | '/settings/account'
    | '/settings/admins'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/settings/routers'
    | '/clerk/sign-in'
    | '/clerk/sign-up'
    | '/clerk/user-management'
    | '/acs'
    | '/apps'
    | '/automation'
    | '/billing'
    | '/chats'
    | '/customers'
    | '/finance'
    | '/genieacs'
    | '/help-center'
    | '/hotspot'
    | '/inventory'
    | '/logs'
    | '/monitoring'
    | '/odp'
    | '/olt'
    | '/pppoe'
    | '/reports'
    | '/settings'
    | '/system-tools'
    | '/tasks'
    | '/tickets'
    | '/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/clerk'
    | '/_authenticated/settings'
    | '/clerk/(auth)'
    | '/clerk/_authenticated'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/network-map'
    | '/_authenticated/'
    | '/_authenticated/customers/by-profile'
    | '/_authenticated/customers/import-export'
    | '/_authenticated/customers/offline'
    | '/_authenticated/customers/online'
    | '/_authenticated/customers/overview'
    | '/_authenticated/errors/$error'
    | '/_authenticated/finance/billing'
    | '/_authenticated/finance/receivable'
    | '/_authenticated/finance/report'
    | '/_authenticated/genieacs/settings'
    | '/_authenticated/odp/capacity'
    | '/_authenticated/pppoe/active'
    | '/_authenticated/pppoe/offline'
    | '/_authenticated/pppoe/profiles'
    | '/_authenticated/pppoe/secrets'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/admins'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/settings/routers'
    | '/clerk/(auth)/sign-in'
    | '/clerk/(auth)/sign-up'
    | '/clerk/_authenticated/user-management'
    | '/_authenticated/acs/'
    | '/_authenticated/apps/'
    | '/_authenticated/automation/'
    | '/_authenticated/billing/'
    | '/_authenticated/chats/'
    | '/_authenticated/customers/'
    | '/_authenticated/finance/'
    | '/_authenticated/genieacs/'
    | '/_authenticated/help-center/'
    | '/_authenticated/hotspot/'
    | '/_authenticated/inventory/'
    | '/_authenticated/logs/'
    | '/_authenticated/monitoring/'
    | '/_authenticated/odp/'
    | '/_authenticated/olt/'
    | '/_authenticated/pppoe/'
    | '/_authenticated/reports/'
    | '/_authenticated/settings/'
    | '/_authenticated/system-tools/'
    | '/_authenticated/tasks/'
    | '/_authenticated/tickets/'
    | '/_authenticated/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  ClerkRouteRoute: typeof ClerkRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/clerk': {
      id: '/clerk'
      path: '/clerk'
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/network-map': {
      id: '/_authenticated/network-map'
      path: '/network-map'
      fullPath: '/network-map'
      preLoaderRoute: typeof AuthenticatedNetworkMapRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clerk/_authenticated': {
      id: '/clerk/_authenticated'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkAuthenticatedRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/clerk/(auth)': {
      id: '/clerk/(auth)'
      path: ''
      fullPath: '/clerk'
      preLoaderRoute: typeof ClerkauthRouteRouteImport
      parentRoute: typeof ClerkRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tickets/': {
      id: '/_authenticated/tickets/'
      path: '/tickets'
      fullPath: '/tickets/'
      preLoaderRoute: typeof AuthenticatedTicketsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks/'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/system-tools/': {
      id: '/_authenticated/system-tools/'
      path: '/system-tools'
      fullPath: '/system-tools/'
      preLoaderRoute: typeof AuthenticatedSystemToolsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/reports/': {
      id: '/_authenticated/reports/'
      path: '/reports'
      fullPath: '/reports/'
      preLoaderRoute: typeof AuthenticatedReportsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pppoe/': {
      id: '/_authenticated/pppoe/'
      path: '/pppoe'
      fullPath: '/pppoe/'
      preLoaderRoute: typeof AuthenticatedPppoeIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/olt/': {
      id: '/_authenticated/olt/'
      path: '/olt'
      fullPath: '/olt/'
      preLoaderRoute: typeof AuthenticatedOltIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/odp/': {
      id: '/_authenticated/odp/'
      path: '/odp'
      fullPath: '/odp/'
      preLoaderRoute: typeof AuthenticatedOdpIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/monitoring/': {
      id: '/_authenticated/monitoring/'
      path: '/monitoring'
      fullPath: '/monitoring/'
      preLoaderRoute: typeof AuthenticatedMonitoringIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs/': {
      id: '/_authenticated/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof AuthenticatedLogsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inventory/': {
      id: '/_authenticated/inventory/'
      path: '/inventory'
      fullPath: '/inventory/'
      preLoaderRoute: typeof AuthenticatedInventoryIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hotspot/': {
      id: '/_authenticated/hotspot/'
      path: '/hotspot'
      fullPath: '/hotspot/'
      preLoaderRoute: typeof AuthenticatedHotspotIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center/'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/genieacs/': {
      id: '/_authenticated/genieacs/'
      path: '/genieacs'
      fullPath: '/genieacs/'
      preLoaderRoute: typeof AuthenticatedGenieacsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/': {
      id: '/_authenticated/finance/'
      path: '/finance'
      fullPath: '/finance/'
      preLoaderRoute: typeof AuthenticatedFinanceIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats/'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing/': {
      id: '/_authenticated/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof AuthenticatedBillingIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automation/': {
      id: '/_authenticated/automation/'
      path: '/automation'
      fullPath: '/automation/'
      preLoaderRoute: typeof AuthenticatedAutomationIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps/'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/acs/': {
      id: '/_authenticated/acs/'
      path: '/acs'
      fullPath: '/acs/'
      preLoaderRoute: typeof AuthenticatedAcsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/clerk/_authenticated/user-management': {
      id: '/clerk/_authenticated/user-management'
      path: '/user-management'
      fullPath: '/clerk/user-management'
      preLoaderRoute: typeof ClerkAuthenticatedUserManagementRouteImport
      parentRoute: typeof ClerkAuthenticatedRouteRoute
    }
    '/clerk/(auth)/sign-up': {
      id: '/clerk/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/clerk/sign-up'
      preLoaderRoute: typeof ClerkauthSignUpRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/clerk/(auth)/sign-in': {
      id: '/clerk/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/clerk/sign-in'
      preLoaderRoute: typeof ClerkauthSignInRouteImport
      parentRoute: typeof ClerkauthRouteRoute
    }
    '/_authenticated/settings/routers': {
      id: '/_authenticated/settings/routers'
      path: '/routers'
      fullPath: '/settings/routers'
      preLoaderRoute: typeof AuthenticatedSettingsRoutersRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/admins': {
      id: '/_authenticated/settings/admins'
      path: '/admins'
      fullPath: '/settings/admins'
      preLoaderRoute: typeof AuthenticatedSettingsAdminsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/pppoe/secrets': {
      id: '/_authenticated/pppoe/secrets'
      path: '/pppoe/secrets'
      fullPath: '/pppoe/secrets'
      preLoaderRoute: typeof AuthenticatedPppoeSecretsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pppoe/profiles': {
      id: '/_authenticated/pppoe/profiles'
      path: '/pppoe/profiles'
      fullPath: '/pppoe/profiles'
      preLoaderRoute: typeof AuthenticatedPppoeProfilesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pppoe/offline': {
      id: '/_authenticated/pppoe/offline'
      path: '/pppoe/offline'
      fullPath: '/pppoe/offline'
      preLoaderRoute: typeof AuthenticatedPppoeOfflineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pppoe/active': {
      id: '/_authenticated/pppoe/active'
      path: '/pppoe/active'
      fullPath: '/pppoe/active'
      preLoaderRoute: typeof AuthenticatedPppoeActiveRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/odp/capacity': {
      id: '/_authenticated/odp/capacity'
      path: '/odp/capacity'
      fullPath: '/odp/capacity'
      preLoaderRoute: typeof AuthenticatedOdpCapacityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/genieacs/settings': {
      id: '/_authenticated/genieacs/settings'
      path: '/genieacs/settings'
      fullPath: '/genieacs/settings'
      preLoaderRoute: typeof AuthenticatedGenieacsSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/report': {
      id: '/_authenticated/finance/report'
      path: '/finance/report'
      fullPath: '/finance/report'
      preLoaderRoute: typeof AuthenticatedFinanceReportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/receivable': {
      id: '/_authenticated/finance/receivable'
      path: '/finance/receivable'
      fullPath: '/finance/receivable'
      preLoaderRoute: typeof AuthenticatedFinanceReceivableRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/finance/billing': {
      id: '/_authenticated/finance/billing'
      path: '/finance/billing'
      fullPath: '/finance/billing'
      preLoaderRoute: typeof AuthenticatedFinanceBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/overview': {
      id: '/_authenticated/customers/overview'
      path: '/customers/overview'
      fullPath: '/customers/overview'
      preLoaderRoute: typeof AuthenticatedCustomersOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/online': {
      id: '/_authenticated/customers/online'
      path: '/customers/online'
      fullPath: '/customers/online'
      preLoaderRoute: typeof AuthenticatedCustomersOnlineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/offline': {
      id: '/_authenticated/customers/offline'
      path: '/customers/offline'
      fullPath: '/customers/offline'
      preLoaderRoute: typeof AuthenticatedCustomersOfflineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/import-export': {
      id: '/_authenticated/customers/import-export'
      path: '/customers/import-export'
      fullPath: '/customers/import-export'
      preLoaderRoute: typeof AuthenticatedCustomersImportExportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/by-profile': {
      id: '/_authenticated/customers/by-profile'
      path: '/customers/by-profile'
      fullPath: '/customers/by-profile'
      preLoaderRoute: typeof AuthenticatedCustomersByProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAdminsRoute: typeof AuthenticatedSettingsAdminsRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsRoutersRoute: typeof AuthenticatedSettingsRoutersRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAdminsRoute: AuthenticatedSettingsAdminsRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsRoutersRoute: AuthenticatedSettingsRoutersRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedNetworkMapRoute: typeof AuthenticatedNetworkMapRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedCustomersByProfileRoute: typeof AuthenticatedCustomersByProfileRoute
  AuthenticatedCustomersImportExportRoute: typeof AuthenticatedCustomersImportExportRoute
  AuthenticatedCustomersOfflineRoute: typeof AuthenticatedCustomersOfflineRoute
  AuthenticatedCustomersOnlineRoute: typeof AuthenticatedCustomersOnlineRoute
  AuthenticatedCustomersOverviewRoute: typeof AuthenticatedCustomersOverviewRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedFinanceBillingRoute: typeof AuthenticatedFinanceBillingRoute
  AuthenticatedFinanceReceivableRoute: typeof AuthenticatedFinanceReceivableRoute
  AuthenticatedFinanceReportRoute: typeof AuthenticatedFinanceReportRoute
  AuthenticatedGenieacsSettingsRoute: typeof AuthenticatedGenieacsSettingsRoute
  AuthenticatedOdpCapacityRoute: typeof AuthenticatedOdpCapacityRoute
  AuthenticatedPppoeActiveRoute: typeof AuthenticatedPppoeActiveRoute
  AuthenticatedPppoeOfflineRoute: typeof AuthenticatedPppoeOfflineRoute
  AuthenticatedPppoeProfilesRoute: typeof AuthenticatedPppoeProfilesRoute
  AuthenticatedPppoeSecretsRoute: typeof AuthenticatedPppoeSecretsRoute
  AuthenticatedAcsIndexRoute: typeof AuthenticatedAcsIndexRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedAutomationIndexRoute: typeof AuthenticatedAutomationIndexRoute
  AuthenticatedBillingIndexRoute: typeof AuthenticatedBillingIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedFinanceIndexRoute: typeof AuthenticatedFinanceIndexRoute
  AuthenticatedGenieacsIndexRoute: typeof AuthenticatedGenieacsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedHotspotIndexRoute: typeof AuthenticatedHotspotIndexRoute
  AuthenticatedInventoryIndexRoute: typeof AuthenticatedInventoryIndexRoute
  AuthenticatedLogsIndexRoute: typeof AuthenticatedLogsIndexRoute
  AuthenticatedMonitoringIndexRoute: typeof AuthenticatedMonitoringIndexRoute
  AuthenticatedOdpIndexRoute: typeof AuthenticatedOdpIndexRoute
  AuthenticatedOltIndexRoute: typeof AuthenticatedOltIndexRoute
  AuthenticatedPppoeIndexRoute: typeof AuthenticatedPppoeIndexRoute
  AuthenticatedReportsIndexRoute: typeof AuthenticatedReportsIndexRoute
  AuthenticatedSystemToolsIndexRoute: typeof AuthenticatedSystemToolsIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedTicketsIndexRoute: typeof AuthenticatedTicketsIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedNetworkMapRoute: AuthenticatedNetworkMapRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedCustomersByProfileRoute: AuthenticatedCustomersByProfileRoute,
  AuthenticatedCustomersImportExportRoute:
    AuthenticatedCustomersImportExportRoute,
  AuthenticatedCustomersOfflineRoute: AuthenticatedCustomersOfflineRoute,
  AuthenticatedCustomersOnlineRoute: AuthenticatedCustomersOnlineRoute,
  AuthenticatedCustomersOverviewRoute: AuthenticatedCustomersOverviewRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedFinanceBillingRoute: AuthenticatedFinanceBillingRoute,
  AuthenticatedFinanceReceivableRoute: AuthenticatedFinanceReceivableRoute,
  AuthenticatedFinanceReportRoute: AuthenticatedFinanceReportRoute,
  AuthenticatedGenieacsSettingsRoute: AuthenticatedGenieacsSettingsRoute,
  AuthenticatedOdpCapacityRoute: AuthenticatedOdpCapacityRoute,
  AuthenticatedPppoeActiveRoute: AuthenticatedPppoeActiveRoute,
  AuthenticatedPppoeOfflineRoute: AuthenticatedPppoeOfflineRoute,
  AuthenticatedPppoeProfilesRoute: AuthenticatedPppoeProfilesRoute,
  AuthenticatedPppoeSecretsRoute: AuthenticatedPppoeSecretsRoute,
  AuthenticatedAcsIndexRoute: AuthenticatedAcsIndexRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedAutomationIndexRoute: AuthenticatedAutomationIndexRoute,
  AuthenticatedBillingIndexRoute: AuthenticatedBillingIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedFinanceIndexRoute: AuthenticatedFinanceIndexRoute,
  AuthenticatedGenieacsIndexRoute: AuthenticatedGenieacsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedHotspotIndexRoute: AuthenticatedHotspotIndexRoute,
  AuthenticatedInventoryIndexRoute: AuthenticatedInventoryIndexRoute,
  AuthenticatedLogsIndexRoute: AuthenticatedLogsIndexRoute,
  AuthenticatedMonitoringIndexRoute: AuthenticatedMonitoringIndexRoute,
  AuthenticatedOdpIndexRoute: AuthenticatedOdpIndexRoute,
  AuthenticatedOltIndexRoute: AuthenticatedOltIndexRoute,
  AuthenticatedPppoeIndexRoute: AuthenticatedPppoeIndexRoute,
  AuthenticatedReportsIndexRoute: AuthenticatedReportsIndexRoute,
  AuthenticatedSystemToolsIndexRoute: AuthenticatedSystemToolsIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedTicketsIndexRoute: AuthenticatedTicketsIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ClerkauthRouteRouteChildren {
  ClerkauthSignInRoute: typeof ClerkauthSignInRoute
  ClerkauthSignUpRoute: typeof ClerkauthSignUpRoute
}

const ClerkauthRouteRouteChildren: ClerkauthRouteRouteChildren = {
  ClerkauthSignInRoute: ClerkauthSignInRoute,
  ClerkauthSignUpRoute: ClerkauthSignUpRoute,
}

const ClerkauthRouteRouteWithChildren = ClerkauthRouteRoute._addFileChildren(
  ClerkauthRouteRouteChildren,
)

interface ClerkAuthenticatedRouteRouteChildren {
  ClerkAuthenticatedUserManagementRoute: typeof ClerkAuthenticatedUserManagementRoute
}

const ClerkAuthenticatedRouteRouteChildren: ClerkAuthenticatedRouteRouteChildren =
  {
    ClerkAuthenticatedUserManagementRoute:
      ClerkAuthenticatedUserManagementRoute,
  }

const ClerkAuthenticatedRouteRouteWithChildren =
  ClerkAuthenticatedRouteRoute._addFileChildren(
    ClerkAuthenticatedRouteRouteChildren,
  )

interface ClerkRouteRouteChildren {
  ClerkauthRouteRoute: typeof ClerkauthRouteRouteWithChildren
  ClerkAuthenticatedRouteRoute: typeof ClerkAuthenticatedRouteRouteWithChildren
}

const ClerkRouteRouteChildren: ClerkRouteRouteChildren = {
  ClerkauthRouteRoute: ClerkauthRouteRouteWithChildren,
  ClerkAuthenticatedRouteRoute: ClerkAuthenticatedRouteRouteWithChildren,
}

const ClerkRouteRouteWithChildren = ClerkRouteRoute._addFileChildren(
  ClerkRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  ClerkRouteRoute: ClerkRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
